#include "agent_state.h"
#include "raymath.h"
#include <cmath>

namespace stellar_agents {

    // ============================================================================
    // CADS ATTRACTOR BEHAVIORAL MATRIX INTERACTION
    // Standard compliance: Fully encapsulated inside the functional project namespace.
    // Implements the non-linear macroscopic force transformation equations.
    // ============================================================================

    // ============================================================================
    // CENTRAL MULTI-BODY FORCE VECTOR FIELD CALCULATOR
    // Compounds the gravitational field potential generated by a microscopic attractor 
    // onto an incoming target state. Marked noexcept for safe thread-pool execution.
    // ============================================================================
    [[nodiscard]] Vector3 CalculateAttractorFieldAcceleration(
        const AgentState& p_attractor,
        const Vector3& p_target_position,
        const float p_gravitational_scalar_mass) noexcept
    {
        // Extract directional vector properties mapping to the phase-space anchor
        const Vector3 displacementDirection = Vector3Subtract(p_attractor.position, p_target_position);
        const float geometricDistanceSq = Vector3LengthSqr(displacementDirection);

        // Core boundary shield: Abort calculation if target penetrates physical singular limits
        // Prevents division-by-zero operations and catastrophic floating-point NaN propagation.
        if (geometricDistanceSq < 0.01f) [[unlikely]] {
            return Vector3Zero();
        }

        // Standardized Newtonian gravitational field scale calculation
        const float scalarDistance = std::sqrt(geometricDistanceSq);
        const float fieldsAccelerationMag = p_gravitational_scalar_mass / geometricDistanceSq;

        // Register-caching optimization: Inline normalization eliminates redundant division passes
        const Vector3 normalizedFieldDir = Vector3Scale(displacementDirection, 1.0f / scalarDistance);

        return Vector3Scale(normalizedFieldDir, fieldsAccelerationMag);
    }

    // ============================================================================
    // ATOMIC ABSORPTION EVENT HORIZON MONITOR
    // Evaluates spatial state proximity constraints against a definitive point of no return.
    // ============================================================================
    [[nodiscard]] bool EvaluateAbsorptionHorizonThreshold(
        const AgentState& p_attractor,
        const Vector3& p_target_position,
        const float p_event_horizon_radius) noexcept
    {
        const float absoluteRange = Vector3Distance(p_target_position, p_attractor.position);
        return (absoluteRange <= p_event_horizon_radius);
    }

} // namespace stellar_agents
